# Generated by Django 5.2.4 on 2025-09-28 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
        ('upload', '0003_alter_upload_file_path_alter_upload_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.upload'),
        ),
    ]
