# Generated by Django 5.2.4 on 2025-09-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feeditem',
            new_name='feed_feedit_score_ba4a84_idx',
            old_name='feeditem_score_id_idx',
        ),
        migrations.RenameIndex(
            model_name='feeditem',
            new_name='feed_feedit_content_91e591_idx',
            old_name='feeditem_ct_oid_idx',
        ),
        migrations.RenameIndex(
            model_name='feeditem',
            new_name='feed_feedit_event_t_6b1fff_idx',
            old_name='feeditem_event_active_idx',
        ),
    ]
