# Generated by Django 5.2.4 on 2025-09-19 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('promotion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotion.promotionpackage'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['content_type', 'object_id'], name='promotion_p_content_9d491c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['type', 'status'], name='promotion_p_type_f21f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_at', 'end_at'], name='promotion_p_start_a_d0b28c_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('content_type', 'object_id', 'status'), name='unique_active_promotion_per_object'),
        ),
    ]
