# Generated by Django 5.2.4 on 2025-09-19 23:32

import django.core.validators
import django.db.models.deletion
import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='uploads/', validators=[upload.models.validate_file_size])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'csv', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', validators=[upload.models.validate_file_size])),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('profile_picture', 'Profile Picture'), ('profile_cover', 'Profile Cover'), ('certificate', 'Certificate'), ('kyc', 'KYC')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
