# Generated by Django 5.2.4 on 2025-09-28 03:26

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(upload_to='public/uploads/', validators=[upload.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='public/thumbnails/', validators=[upload.models.validate_file_size]),
        ),
    ]
