# Generated by Django 5.2.6 on 2025-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
