# Generated by Django 5.2.4 on 2025-09-28 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_fix_city_field'),
        ('skill', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Nice to have'), (2, 'Preferred'), (3, 'Important'), (4, 'Required'), (5, 'Critical')], default=3, help_text='How important this skill is for the job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='required_proficiency',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1, help_text='Required proficiency level'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='years_required',
            field=models.FloatField(default=0.0, help_text='Years of experience required'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='last_used',
            field=models.DateField(blank=True, help_text='Last time this skill was used', null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='proficiency_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1, help_text='Skill proficiency level (1-5)'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userskill',
            name='years_experience',
            field=models.FloatField(default=0.0, help_text='Years of experience with this skill'),
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
